name: Auto Merge PRs

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  auto-merge:
    if: github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge PR if checks pass
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
